# This file was generated by GoReleaser. DO NOT EDIT.
cask "dockportless" do
  name "dockportless"
  desc "Compose-compatible local service router with auto port assignment"
  homepage "https://github.com/mazrean/dockportless"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dockportless"

  on_macos do
    on_intel do
      url "https://github.com/mazrean/dockportless/releases/download/v#{version}/dockportless_#{version}_darwin_amd64.tar.gz"
      sha256 "bca24e9bf8e51b5caf27543a420a6e74262a77fc3eae9c6397fecab52d5de220"
    end
    on_arm do
      url "https://github.com/mazrean/dockportless/releases/download/v#{version}/dockportless_#{version}_darwin_arm64.tar.gz"
      sha256 "35f0a2e9f721fc67180d7504a6d0ff421f5c57512efd7f92f9c00b0de22e590e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mazrean/dockportless/releases/download/v#{version}/dockportless_#{version}_linux_amd64.tar.gz"
      sha256 "b2ddcbfb733e8ce7c1bfbc9491940e9fc6f578ae2bd1f6e6d50cef2f71358cdc"
    end
    on_arm do
      url "https://github.com/mazrean/dockportless/releases/download/v#{version}/dockportless_#{version}_linux_arm64.tar.gz"
      sha256 "025d03ebbdaf55da9b9bdd1ed2bee52cb07894c0aa5a3e48c8204fe4c4082e85"
    end
  end

  # No zap stanza required
end
