# This file was generated by GoReleaser. DO NOT EDIT.
cask "kessoku" do
  name "kessoku"
  desc "A CLI tool for managing kessoku"
  homepage "https://github.com/mazrean/kessoku"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kessoku"

  on_macos do
    on_intel do
      url "https://github.com/mazrean/kessoku/releases/download/v#{version}/kessoku_Darwin_x86_64.tar.gz"
      sha256 "e60632378dfce4ed32eb255d95484630f1580d50c282c75b4ed685229887d39f"
    end
    on_arm do
      url "https://github.com/mazrean/kessoku/releases/download/v#{version}/kessoku_Darwin_arm64.tar.gz"
      sha256 "eade150c94d7f4f9ca16b4ced6d48239f2d27f7a1d2f1738225fd402ef111880"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mazrean/kessoku/releases/download/v#{version}/kessoku_Linux_x86_64.tar.gz"
      sha256 "97a5e25d9ce9ef162798610ecb40a63d5ea448bd541102491890137098893f17"
    end
    on_arm do
      url "https://github.com/mazrean/kessoku/releases/download/v#{version}/kessoku_Linux_arm64.tar.gz"
      sha256 "a3192fd39a2a6f72b4243a3e62dd4c5413d93f83d9fa8a2446a34253dc3c5cf0"
    end
  end

  # No zap stanza required
end
