# This file was generated by GoReleaser. DO NOT EDIT.
cask "kessoku" do
  desc "A CLI tool for managing kessoku"
  homepage "https://github.com/mazrean/kessoku"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kessoku"

  on_macos do
    on_intel do
      url "https://github.com/mazrean/kessoku/releases/download/v0.1.0/kessoku_Darwin_x86_64.tar.gz"
      sha256 "8f8f3d49baa9a54fb8b5bd115e10126f2a67cdfad1c9a2bf6adc0c3221734805"
    end
    on_arm do
      url "https://github.com/mazrean/kessoku/releases/download/v0.1.0/kessoku_Darwin_arm64.tar.gz"
      sha256 "b0d256688abfc22fc4234a6a0aceed5d3c81ac8530ab51b8064275b1cd3c4eff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mazrean/kessoku/releases/download/v0.1.0/kessoku_Linux_x86_64.tar.gz"
      sha256 "9249e938c9b901879d7233a595784260d69fd435b271976e833d6f9222d123d7"
    end
    on_arm do
      url "https://github.com/mazrean/kessoku/releases/download/v0.1.0/kessoku_Linux_arm64.tar.gz"
      sha256 "02d7e9724ab2ab7731bc3a8fca43b39cb6af0f8f22e1c1dba8d6a9960f1ddac7"
    end
  end

  # No zap stanza required
end
