# This file was generated by GoReleaser. DO NOT EDIT.
cask "odjson" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "089034cff54ad7ba42d788c87257acff133d82a8c46a745a15655db9bdb7ca60"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec763523b9577156f12ec8953537325ac2a64748118c4eb654cac26cb6f54f20"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "abe9a923d530e489a870c9a2e8dd4276c9bff3663545203531acd5435b2da585"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "754545527b66a87803345f92ece407368505a5caefe03477909c935efa855788"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_amd64.tar.gz"
    end
  end

  name "odjson"
  desc "Reflection-free JSON marshal/unmarshal code generator for Go"
  homepage "https://github.com/mazrean/odjson"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odjson"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odjson"]
    end
  end

  # No zap stanza required
end
