# This file was generated by GoReleaser. DO NOT EDIT.
cask "odjson" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9140144178415853ff0fbcc23848817cc349c1dc9f13a2ff3161debdce72cb13"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "127787b8ff48d2ab6273b37920d63664dc465bb9914b56149785b91aacb435da"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "14cd333f8c51c11ec48fd53ff86dd99a7b25598ee0353c38ea032f18bca35202"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcdccf9ca524915b5d1afafe363079d1cab4cf7cf4810c4b93ef2c2a4069999d"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_amd64.tar.gz"
    end
  end

  name "odjson"
  desc "Reflection-free JSON marshal/unmarshal code generator for Go"
  homepage "https://github.com/mazrean/odjson"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odjson"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odjson"]
    end
  end

  # No zap stanza required
end
