# This file was generated by GoReleaser. DO NOT EDIT.
cask "odjson" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "8e797d4102a73707cd2107ff77cf37304c536f6caafbe7ec9881e72b1c811817"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b302b2a837d5b64ba1254c7a70ca90e1e56c78a2f1e809bcca4d11cd573d9765"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "30023011b006a7bf4ee24ea11ed890ac1da1f1878a513276d871bdd44a5c3ef9"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d05ac7bf8de1cca0398b149f5080d46e4de33f4fb965e08b10a51d201733a4da"
      url "https://github.com/mazrean/odjson/releases/download/v#{version}/odjson_#{version}_linux_amd64.tar.gz"
    end
  end

  name "odjson"
  desc "Reflection-free JSON marshal/unmarshal code generator for Go"
  homepage "https://github.com/mazrean/odjson"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odjson"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odjson"]
    end
  end

  # No zap stanza required
end
