# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills-pkg" do
  name "skills-pkg"
  desc "Agent Skills package manager for Claude Code and Codex CLI"
  homepage "https://github.com/mazrean/skills-pkg"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills-pkg"

  on_macos do
    on_intel do
      url "https://github.com/mazrean/skills-pkg/releases/download/v#{version}/skills-pkg_Darwin_x86_64.tar.gz"
      sha256 "bcb908b2bf4d629e414b1f7ddc5b321d52376d9f22ae81833508bc6b80afd6f6"
    end
    on_arm do
      url "https://github.com/mazrean/skills-pkg/releases/download/v#{version}/skills-pkg_Darwin_arm64.tar.gz"
      sha256 "b722d5a0de538206b380dfd8f5bf380c6874fe1ee13fde779f4d939ab1b5ed2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mazrean/skills-pkg/releases/download/v#{version}/skills-pkg_Linux_x86_64.tar.gz"
      sha256 "dc4a78932c52223b77380ad0fb09e0c1ded8395a0800469e0b69606692b89f62"
    end
    on_arm do
      url "https://github.com/mazrean/skills-pkg/releases/download/v#{version}/skills-pkg_Linux_arm64.tar.gz"
      sha256 "0d0fd9de7d094528e62a03ae50ba836df8b5d1957e24fdbd1ebb2418f5f8ad4e"
    end
  end

  # No zap stanza required
end
