# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTarmaq < Formula
  desc "A Model Context Protocol (MCP) server that suggests files related to files that have already been modified."
  homepage "https://github.com/mazrean/mcp-tarmaq"
  version "0.1.0-alpha10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mazrean/mcp-tarmaq/releases/download/v0.1.0-alpha10/mcp-tarmaq_Darwin_x86_64.tar.gz"
      sha256 "0e679f5dfba2265309c7ae68cd8fb1f14cb2500e7e65b6c2643c538fff292409"

      def install
        bin.install "mcp-tarmaq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mazrean/mcp-tarmaq/releases/download/v0.1.0-alpha10/mcp-tarmaq_Darwin_arm64.tar.gz"
      sha256 "37817f3512c188181d7221b17563e4a1d8f89a287010bd8c484526e5111b4501"

      def install
        bin.install "mcp-tarmaq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazrean/mcp-tarmaq/releases/download/v0.1.0-alpha10/mcp-tarmaq_Linux_x86_64.tar.gz"
        sha256 "6fe0ed053ee70f707ad4c25e67b30177ff8c10d82b127016b9db894cbde4fbb5"

        def install
          bin.install "mcp-tarmaq"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/mazrean/mcp-tarmaq/releases/download/v0.1.0-alpha10/mcp-tarmaq_Linux_armv7.tar.gz"
        sha256 "5c4f6d5ff3c2f299dd76ee2c241fda080f483699f324af31c89353577671952c"

        def install
          bin.install "mcp-tarmaq"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazrean/mcp-tarmaq/releases/download/v0.1.0-alpha10/mcp-tarmaq_Linux_arm64.tar.gz"
        sha256 "782821c05fd7f32f392c5ae246072cf635c0c074f87e597605801fafed8e88be"

        def install
          bin.install "mcp-tarmaq"
        end
      end
    end
  end

  test do
    system "#{bin}/mcp-tarmaq -v"
  end
end
